"""added unique_order_constraint

Revision ID: 95c4866899f0
Revises: 
Create Date: 2024-01-30 08:40:13.190211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c4866899f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_order_constraint', ['name', 'checkin_date', 'checkout_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('unique_order_constraint', type_='unique')

    # ### end Alembic commands ###
